export const GENERATE_NEW_ARRAY = "ARRAY/GENERATE_NEW_ARRAY";
export const CHANGE_ARRAY_SIZE = "ARRAY/CHANGE_ARRAY_SIZE";
export const SET_NEW_ARRAY = "ARRAY/SET_NEW_ARRAY";
export const SET_SORTING_ACTIVE = "ARRAY/SET_SORTING_ACTIVE";
export const SET_SORTING_INACTIVE = "ARRAY/SET_SORTING_INACTIVE";

export const CHANGE_SORTING_SPEED = "SPEED/CHANGE_SORTING_SPEED";
